FROM node:18-alpine

# Set working directory
WORKDIR /app

# Install dependencies
COPY package.json package-lock.json ./
RUN npm install

# Copy the rest of the code
COPY . .

# Start development server
CMD ["npm", "run", "dev"]

# Expose port
EXPOSE 3000 