version: '3.8'

services:
  # Frontend application
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: agromark-frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:5000/api
    depends_on:
      - backend

  # Backend API server
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: agromark-backend
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/agromark
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=development_secret_key
      - FRONTEND_URL=http://localhost:3000
      - SOLANA_NETWORK=devnet
      - MARKETPLACE_PROGRAM_ID=11111111111111111111111111111111
      - ESCROW_PROGRAM_ID=11111111111111111111111111111111
    depends_on:
      - postgres
      - redis

  # Database
  postgres:
    image: postgres:14-alpine
    container_name: agromark-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=agromark
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Cache server
  redis:
    image: redis:7-alpine
    container_name: agromark-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # Adminer for database management (optional)
  adminer:
    image: adminer
    container_name: agromark-adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  # Solana validator for local development (optional)
  solana:
    image: solanalabs/solana:stable
    container_name: agromark-solana
    command: solana-test-validator
    ports:
      - "8899:8899"
      - "8900:8900"
    volumes:
      - solana_data:/solana

volumes:
  postgres_data:
  redis_data:
  solana_data: 